README.md, package-lock.json, package.json
This is the initial change to make `@fullstory/babel-plugin-annotate-react` a dep for our RN plugin.
We will need a FS plugin update to take advantage of this, so no need to create a new tag for this release just yet.
=> add @fullstory/babel-plugin-annotate-react as a dependency

ios/FullStory.h, ios/FullStory.m
Pairs with jwise/unswizzle-react-native branch in FullStory.framework.
Note that modifying an fsAttribute is an untested codepath -- I don't see a test for that in App.js.  I'll work on testing that out, in parallel.
=> iOS: Move swizzles out of FullStory.framework, and implement fsTagName and fsAttribute.

README.md, android/src/main/java/com/fullstory/reactnative/FullStoryModule.java, android/src/main/java/com/fullstory/reactnative/FullStoryNativeProps.java, android/src/main/java/com/fullstory/reactnative/FullStoryPackage.java, android/src/main/java/com/fullstory/reactnative/NativeProp.java, ios/FullStory.h, ios/FullStory.m
In conjunction with the upcoming FS `1.5.5` release, we are moving the NativeProps receivers to this plugin and out from the FS plugin.
Additionally, this PR adds the FS.onReady API.
=> Add `onReady` and move the NativeProps handlers to this plugin

CHANGELOG.md, package-lock.json, package.json
Using `^` breaks the newest version of `npm`, which will strictly check for peer dependencies. This change addresses that by using `>=`.
=> Update React Native dependency declarations

CHANGELOG.md, android/src/main/java/com/fullstory/reactnative/FullStoryModule.java, ios/FullStory.m, package-lock.json, package.json, src/index.js
This PR exposes the FS.log infrastructure to React Native Javascript.
The log method takes an int enum and will default to `Info` if the int is invalid.
Usage:
```
import FullStory from '@fullstory/react-native';
// Exercise the logging
FullStory.log(FullStory.LogLevel.Log, 'Log at Log (on iOS, clamps to Debug)');
FullStory.log(FullStory.LogLevel.Debug, 'Log at Debug');
FullStory.log(FullStory.LogLevel.Info, 'Log at Info');
FullStory.log(FullStory.LogLevel.Warn, 'Log at Warn');
FullStory.log(FullStory.LogLevel.Error, 'Log at Error');
FullStory.log(FullStory.LogLevel.Assert, 'Log at Assert (on Android, clamps to Error)');
FullStory.log(-1, 'Log at -1 (defaults to Info)');
FullStory.log(10, 'Log at 10 (defaults to Info)');
```
=> add the ability to invoke FS.log via javascript

src/index.d.ts
This PR auto-adds our base attributes to the global TS namespace, so our users won't have to do it manually.
=> add our base attributes to the global namespace

CHANGELOG.md, package-lock.json, package.json
This PR releases 1.0.5, which just updated our `@fullstory/babel-plugin-react-native` minimum to 1.0.2.
=> release 1.0.5

CHANGELOG.md, package-lock.json, package.json, src/index.d.ts
This PR adds resetIdleTimer to the typescript type definitions. I will use this PR as a 1.0.7 release PR once this is approved.
=> add resetIdleTimer to the typescript definitions

.circleci/config.yml, package-lock.json, package.json
Fix breaking circleCI pipeline and add test job.
1. Needed to upgrade to node16 environment to use `import fs from "fs/promises";`
2. Needed to add TypeScript as dependency to use `ts-jest`.
=> Fix breaking circleCI pipeline and add test job

package-lock.json, package.json
Update our expo dependencies based on official recommendation from [docs](https://docs.expo.dev/config-plugins/development-and-debugging/#install-dependencies). 
Override two vulnerable peer dependencies not yet patched officially.
=> update dependencies for vulnerabilities

plugin/build/withFullStoryAndroid.js, plugin/src/__tests__/withFullStoryAndroid.test.ts, plugin/src/withFullStoryAndroid.ts
From #60 ,
The `recordOnStart` option is true by default and can optionally be disabled. The previous implementation wouldn't set the option in the app's `build.gradle` when provided a `false` value, so this PR fixes that implementation and adds a simple test.
Original contributor is inactive. Rebased off master so we can merge his contribution.
=> Fix expo plugin record on start arg

android/src/main/java/com/fullstory/reactnative/FullStoryPackage.java
The recent `1.2.0` change prevented Native Module auto-linking for RN versions <=0.64. This caused RN apps to ignore our plugin and skipped our Native Prop rewriting, which caused API's to be unavailable. 
* remove lambda return syntax to support older Java versions
* implement `ReactPackage` so that older RN versions will auto link package
RN 63: https://app.staging.fullstory.com/ui/KWH/session/4919025558028288:5155602586599424
RN 64: https://app.staging.fullstory.com/ui/KWH/session/5415893039775744:6641882059177984
RN65: https://app.fullstory.com/ui/H0SZW/session/5320765840961536:6169443359141888
RN69: https://app.staging.fullstory.com/ui/KWH/session/5010370993782784:4913375658573824
RN72 Non-Fabric: https://app.staging.fullstory.com/ui/KWH/session/6630689065336832:4980603036827648
RN72 …
=> fix turbo module compatibility

android/src/legacy/java/com/FullStoryModule.java, android/src/main/java/com/fullstory/reactnative/FullStoryModuleImpl.java, android/src/turbo/java/com/FullStoryModule.java, src/FSPage.ts, src/NativeFullStory.ts, src/index.d.ts, src/index.js
Post design doc approval:
- update legacy RN native module method declarations
- replace System.out with android.util.Log
- initialize reflected methods once
- getUUID is async
- fix page properties merge
- add TS FSPage types
RN Fabric [session](https://app.staging.fullstory.com/ui/KWH/session/6630689065336832:5887655561068544)
RN old architecture [session](https://app.staging.fullstory.com/ui/KWH/session/4994683218886656:5840084033536000)
This merges into branch `add-pages-api`. Additional work needed:
- iOS implementation
- add a testing framework to this plugin to test FSPage
=> Add Android pages implementation

babel.config.js, jest.config.js, package-lock.json, package.json, setupTests.js, src/FSPage.ts, src/__tests__/FSPage.test.ts
Improve FSPage typing and add jest testing.
=> Improve Pages types and add testing

ios/FullStory.mm, package-lock.json, package.json, src/index.ts
See [design doc](https://docs.google.com/document/d/1OIahWaovsaoqdWr12zmJRcF0LZlOzoDuLcv6FPzz_WY)
This work seeks to solve an issue where props are statically defined in Fabric and cannot set our FullStory props onto views.
=> iOS Fabric implementation

fullstory_react-native.podspec, ios/FullStory.mm
1. Remove explicit folly version from podspec. This fixes a folly dependency issue in RN 73.
2. Use `install_modules_dependencies` from RN to install dependencies if possible
3. Remove "Contact FullStory support" from `RCTViewComponentView` swizzle message since we currently do not swizzle subclasses by design. cc @martin-fs 
Tested on RN 63, RN 69, RN 73
=> Update podspec, update Fabric swizzle message

CHANGELOG.md, package-lock.json, package.json
`1.4.0`'s [release](https://github.com/fullstorydev/fullstory-react-native/pull/81/files) did not include a dependency update made to `@fullstory/babel-plugin-react-native`, since that update was made in the same PR as the release.
=> release 1.4.1

.circleci/config.yml
Dependency [react-native-cli](https://github.com/react-native-community/cli/issues/2294) `ip` received a security warning which the community is in the process of resolving. We're raising the audit level here to prevent us from being blocked from making updates.
=> Raise audit level to pass CI

ios/FullStory.mm
To support React Native Navigation screen selectors, we'll need to assign the screen name value from `layoutInfo.name` to fsAttributes, where we'll read it from the SDK.
Paired with [PR](https://github.com/cowpaths/mn/pull/74866)
=> RNN selector support

package-lock.json, package.json, src/index.ts
React `18.3.0` moved the `currentProps` object into the `canonical` property. [PR here](https://github.com/facebook/react/pull/26408).
This is causing us to not be able to read our FS attributes off of the component instance. 
RN `0.74.0` has a new function ([PR here](https://github.com/facebook/react-native/pull/41786)) called `getInternalInstanceHandleFromPublicInstance` that will help us get at the `currentProps` property. If `getInternalInstanceHandleFromPublicInstance` exists, we'll try to use it as it's indicative of the new Fabric Component Tree.
=> support RN 74 on iOS

src/index.ts
Moving `require('react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance').getInternalInstanceHandleFromPublicInstance;` to outside the function body, so that it only needs to be imported once.
When the import was inside the function body, metro could not resolve this inline require (not sure why).
The current version works with RN 74, Old and New architecture, and RN versions <= 73 with Old architecture. 
This fixes RN versions <= 73 with New architecture.
RN 66 [session](https://app.staging.fullstory.com/ui/3RWN/session/5920355914809344:684040693366613108) (old)
RN 72 [session](https://app.staging.fullstory.com/ui/KWH/session/5896947218972672:3533583341178842338) (new)
RN 72 [[session](https://app.staging.fullstory.com/ui/KWH/session/5896947218972672:635332 …
=> bugfix: fix inline require

plugin/src/index.ts, plugin/src/withFullStoryIos.ts
This PR adds in some missing plist options that we required in our product, the config fields are:
- includeAssets
- workaroundRNSVGCapture
- workaroundWKUserContentControllerRemoveAllUserScripts
=> fix: add missing plist configs for ios

plugin/build/index.d.ts, plugin/build/withFullStoryAndroid.js, plugin/build/withFullStoryIos.js, plugin/src/__tests__/fixtures/fullstoryConfig.json, plugin/src/__tests__/withFullStoryAndroid.test.ts, plugin/src/index.ts, plugin/src/withFullStoryAndroid.ts, plugin/src/withFullStoryIos.ts
It makes sense to separate custom configs by platform, so that they're not being applied to both platforms at once.
=> separate custom configs by platform

android/src/legacy/java/com/FullStoryPrivateModule.java, android/src/main/java/com/fullstory/reactnative/FullStoryPackage.java, android/src/main/java/com/fullstory/reactnative/FullStoryPrivateModuleImpl.java, android/src/turbo/java/com/FullStoryPrivateModule.java, ios/FullStory.h, ios/FullStory.mm, package.json, src/NativeFullStoryPrivate.ts, src/index.ts
This PR adds a new exported module named `PrivateInterface`. On iOS, no methods are exported. On Android, `onFSPressForward` is exported.
If this method is called, then we use reflection to find a new (in the upcoming `1.49.0` FS release) `FS.reactNative_exec_onFsPressForward_direct` method and invoke the press forwarding.
Note: This also changes our minimum supported RN version to `0.66.0`.
=> update the RN plugin to receive clicks from JS

android/src/main/java/com/fullstory/reactnative/FullStoryPrivateModuleImpl.java
Currently, calling `uiManager.resolveView(reactTag);` causes React Native to throw a `SoftException`, because it [expects](https://github.com/facebook/react-native/blob/0fd4a9447e432b8c537825f571409f56ae63dc90/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/fabric/FabricUIManager.java#L927) `FabricUIManager.resolveView` to be run on the UI thread. 
To avoid this error, we run our click handler on the UI thread.
Still needs to be tested on all the RN versions, but looking for early feedback on this.
[RN 74 Fabric Session](https://app.staging.fullstory.com/ui/KWH/session/3280449202851595977:4543370893277384711)
[RN 66 Session ](https://app.staging.fullstory.com/ui/KWH/session/3378027069031434083:8327334863529245776)
=> run click handler on UI thread

ios/FullStory.mm
VAL-8909
View controllers manage a `view`, including loading it if necessary via `loadView` when the `view` property is accessed. React Native Navigation's `RNNComponentViewController` calls `renderReactViewIfNeeded` to load the view, which typically loads both the view controller's `view` and a `reactView`.
However, it's possible for this RNN view controller to end up with a `reactView` but no `view` - my best guess is we're seeing it after UIKit has partially unloaded the view controller, but it of course doesn't know about the `reactView` field. Triggering `loadView` in such a state actually does nothing, because [there's an initial check for the presence of `reactView` ](https://github.com/wix/react-native-navigation/blob/efee2bdb8af6b0c3696c1c611f4b1492f60abbca/lib/ios/RNNComponentVie …
=> Avoid a potential initialization loop

src/FSPage.ts, src/index.ts, src/utils.ts
RN versions >=0.77 will use global.RN$Bridgeless as an indicator of whether New Architecture is enabled.
=> Fix new architecture detection

.circleci/config.yml, package-lock.json, src/NativeFullStory.ts, src/fullstoryInterface.ts, src/index.ts, src/index.web.ts
[VAL-9294](https://fullstory.atlassian.net/browse/VAL-9294)
This work aims at avoiding module resolution errors when Expo's metro is bundling for a web environment. We create an `index.web.ts` and react native will automatically resolve to that file in a web environment, which will avoid importing native only modules.
=> VAL-9294: Provide noop API for web environments

ios/FullStory.mm
A customer experienced a rare crash that seems consistent with a race in accessing the resolve callback passed in from the javascript onReady API. If called at just the right time, the delegate could try to invoke the callback at the same time as the code setting the callback, leading to it being nulled out just before one of them calls it.
=> Synchronize invoking the onReady callback

src/fullstoryInterface.ts
React 19 has removed `JSX` from the global namespace. 
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript
Thanks @bhandanyan-nomad for raising this issue.
=> update types for React 19

package-lock.json, src/FSPage.ts, src/fullstoryInterface.ts, src/index.ts, src/utils.ts
https://fullstory.slack.com/archives/C1DAWDPM3/p1749760541114209
**Context**
Customer reported a metro import error for version RN 72. This doesn't error doesn't exist in newer versions of React Native (79, 80), so the issue should be resolved by metro. This refactor is for backwards compatibility.
**Issue**
In `index.ts`, the existence of this import: `getInternalInstanceHandleFromPublicInstance =
require('react-native/Libraries/ReactNative/ReactFabricPublicInstance/ReactFabricPublicInstance').getInternalInstanceHandleFromPublicInstance;` causes older metro to fail to resolve importing `LogLevel`. 
**Solution**
This issue seems to resolve itself if `LogLevel` is moved to a file that exports another value. This PR simply moves `global` and `isTurboModuleEnabled` to another file, so that …
=> WECA-1403: fix metro import error

package-lock.json, src/index.ts
Through testing, I found that since our babel plugin adds the `ref` wrapper (`applyFSPropertiesWithRef`) at the source code of Element creation in React, it causes Components to use our `ref` wrapper multiple times, which results in View commands to fire multiple times when they don't need to.
There is a race condition in React Native view commands leading to this issue:
https://fullstory.atlassian.net/browse/VAL-9554
By reducing unnecessary and duplicate calls to View commands, we can hopefully better avoid this race condition.
iOS session: https://app.staging.fullstory.com/ui/3RWN/session/5189324896763904:4513279741166412317
In this session, we avoid around 3300 duplicate calls to View Commands.
=> Check for already wrapped ref

ios/FullStory.mm, src/index.ts
In addition to the swizzle commands, we're exporting FS_REF_SYMBOL so that the babel plugin has access to it to fix another issue.
=> VAL-9669: add lottie and webview to swizzle
